version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5.5
    ports:
      - "8080:80" # Page web
      - "8082:8080" # UI
    command:
      - --entrypoints.web.address=:80
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false
    depends_on:
      - prizes

  portainer:
    image: portainer/portainer-ce:2.11.0-alpine
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.rule=Host(`api.labo.ch`) && PathPrefix(`/ui`)

      - traefik.http.routers.portainer.middlewares=portainer-prefix-remover
      - traefik.http.middlewares.portainer-prefix-remover.chain.middlewares=strip-prefix-1,strip-prefix-2
      - traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$
      - traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$${1}/
      - traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true
      - traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+
    depends_on:
      - traefik

  prizes:
    image: api/node-express
    build: ../node-express/.
    labels:
      - traefik.enable=true
      - traefik.http.routers.prizes.entrypoints=web
      - traefik.http.services.prizes.loadbalancer.server.port=3000
      - traefik.http.routers.prizes.rule=Host(`api.labo.ch`) && PathPrefix(`/api/prize`)
      - traefik.http.routers.prizes.middlewares=prizes-prefix-remover
      - traefik.http.middlewares.prizes-prefix-remover.stripprefix.prefixes=/api/prize
      - traefik.http.middlewares.prizes-prefix-remover.stripprefix.forceSlash=false

  frontend:
    image: api/apache-ajax
    build: ../apache-ajax/.
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`api.labo.ch`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.sticky.cookie=true

volumes:
  portainer_data: